// Generated by CIRCT unknown git version
module SpMM(	// <stdin>:2295:3
  input        clock,	// <stdin>:2296:11
               reset,	// <stdin>:2297:11
               io_start,	// src/main/scala/spmm/SpMM.scala:31:14
  output       io_inputReady,	// src/main/scala/spmm/SpMM.scala:31:14
  input  [7:0] io_lhsRowIdx_0,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_1,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_2,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_3,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_4,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_5,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_6,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_7,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_8,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_9,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_10,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_11,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_12,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_13,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_14,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsRowIdx_15,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_0,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_1,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_2,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_3,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_4,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_5,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_6,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_7,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_8,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_9,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_10,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_11,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_12,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_13,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_14,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsCol_15,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_0_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_1_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_2_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_3_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_4_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_5_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_6_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_7_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_8_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_9_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_10_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_11_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_12_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_13_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_14_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_lhsData_15_data,	// src/main/scala/spmm/SpMM.scala:31:14
  input        io_rhsReset,	// src/main/scala/spmm/SpMM.scala:31:14
  input  [7:0] io_rhsData_0_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_1_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_2_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_3_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_4_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_5_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_6_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_7_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_8_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_9_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_10_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_11_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_12_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_13_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_14_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_rhsData_15_data,	// src/main/scala/spmm/SpMM.scala:31:14
  output [7:0] io_outData_0_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_1_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_2_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_3_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_4_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_5_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_6_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_7_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_8_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_9_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_10_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_11_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_12_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_13_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_14_data,	// src/main/scala/spmm/SpMM.scala:31:14
               io_outData_15_data,	// src/main/scala/spmm/SpMM.scala:31:14
  output       io_outValid	// src/main/scala/spmm/SpMM.scala:31:14
);

  assign io_inputReady = 1'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_0_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_1_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_2_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_3_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_4_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_5_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_6_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_7_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_8_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_9_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_10_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_11_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_12_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_13_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_14_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outData_15_data = 8'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
  assign io_outValid = 1'h0;	// <stdin>:2295:3, src/main/scala/spmm/Arith.scala:10:14
endmodule

