// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SpMM(	// <stdin>:3:3
  input        clock,	// <stdin>:4:11
               reset,	// <stdin>:5:11
               io_start,	// src/main/scala/spmm/SpMM.scala:22:16
  output       io_inputReady,	// src/main/scala/spmm/SpMM.scala:22:16
  input  [7:0] io_lhsRowIdx_0,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_1,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_2,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_3,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_4,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_5,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_6,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_7,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_8,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_9,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_10,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_11,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_12,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_13,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_14,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsRowIdx_15,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_0,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_1,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_2,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_3,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_4,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_5,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_6,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_7,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_8,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_9,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_10,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_11,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_12,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_13,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_14,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsCol_15,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_0_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_1_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_2_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_3_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_4_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_5_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_6_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_7_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_8_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_9_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_10_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_11_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_12_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_13_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_14_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_lhsData_15_data,	// src/main/scala/spmm/SpMM.scala:22:16
  input        io_rhsReset,	// src/main/scala/spmm/SpMM.scala:22:16
  input  [7:0] io_rhsData_0_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_1_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_2_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_3_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_4_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_5_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_6_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_7_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_8_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_9_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_10_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_11_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_12_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_13_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_14_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_rhsData_15_data,	// src/main/scala/spmm/SpMM.scala:22:16
  output [7:0] io_outData_0_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_1_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_2_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_3_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_4_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_5_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_6_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_7_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_8_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_9_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_10_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_11_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_12_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_13_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_14_data,	// src/main/scala/spmm/SpMM.scala:22:16
               io_outData_15_data,	// src/main/scala/spmm/SpMM.scala:22:16
  output       io_outValid	// src/main/scala/spmm/SpMM.scala:22:16
);

  reg [7:0] io_outData_0_ret_data_REG;	// src/main/scala/spmm/Arith.scala:22:24
  always @(posedge clock)	// <stdin>:4:11
    io_outData_0_ret_data_REG <= io_lhsData_0_data + io_lhsData_1_data;	// src/main/scala/spmm/Arith.scala:22:24, :25:46
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:3:3
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:3:3
      `FIRRTL_BEFORE_INITIAL	// <stdin>:3:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:3:3
      automatic logic [31:0] _RANDOM[0:0];	// <stdin>:3:3
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:3:3
        `INIT_RANDOM_PROLOG_	// <stdin>:3:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:3:3
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// <stdin>:3:3
        io_outData_0_ret_data_REG = _RANDOM[/*Zero width*/ 1'b0][7:0];	// <stdin>:3:3, src/main/scala/spmm/Arith.scala:22:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:3:3
      `FIRRTL_AFTER_INITIAL	// <stdin>:3:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_inputReady = 1'h0;	// <stdin>:3:3
  assign io_outData_0_data = io_outData_0_ret_data_REG;	// <stdin>:3:3, src/main/scala/spmm/Arith.scala:22:24
  assign io_outData_1_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_2_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_3_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_4_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_5_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_6_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_7_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_8_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_9_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_10_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_11_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_12_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_13_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_14_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outData_15_data = 8'h0;	// <stdin>:3:3, src/main/scala/spmm/SpMM.scala:25:16
  assign io_outValid = 1'h0;	// <stdin>:3:3
endmodule

